---
title: "make_mutation_tree"
author: "Matthew Davis"
date: "2024-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
## Libraries
```{r, message=FALSE}
library(ape)
library(phangorn)
library(polymorphology2)
library(ggtree)
library(tidyverse)
```

## Functions
```{r}
gene_body_source_type <- function(source_type) {

  # Filter mutations for the given source type
  muts_filtered <- unique(mutations_filt[Source_type == source_type, .(CHROM, POS, effect)])
  muts_filtered$CHROM <- as.numeric(as.character(muts_filtered$CHROM))
  gene_windows$CHROM <- as.numeric(as.character(gene_windows$CHROM))

  # Calculate mutations in gene windows
  gene_windows_mutations <- sites_in_features(gene_windows, sites = muts_filtered, mode = "counts")
  gene_windows$muts <- gene_windows_mutations$counts[match(gene_windows$ID, gene_windows_mutations$ID)]

  # Plot and summarize the feature windows
  summary <- plot_feature_windows(gene_windows, variable = "muts", mode = "percent")$summary
  maxpos <- max(summary$RELATIVEPOS)

  # Chi-squared test
  chisq.test(summary[, 4:5])

  # Generate the plot
  plot <- ggplot(summary, aes(x = RELATIVEPOS, y = y, fill = REGION == "gene body")) +
    geom_bar(stat = "identity", col = "black", width = 0.75) +
    geom_vline(xintercept = c(maxpos / 3, maxpos / 3 * 2) + 0.5, linetype = "dashed") +
    theme_classic(base_size = 6) +
    scale_x_continuous(breaks = c(1, (maxpos / 3) + 0.5, (maxpos / 3 * 2) + 0.5, maxpos),
                       labels = c("-5kb", "START", "STOP", "+5kb")) +
    scale_fill_manual(values = c("gray", "green4"), guide="none") +
    ggtitle(paste("Ns =", sum(muts_filtered$effect == "Non-Syn"), "S =", sum(muts_filtered$effect == "Syn")))

  return(plot)
}

fasta_trimer_freq<-function(fasta, stop = NULL){
  fasta_windows<-rbindlist(lapply(1:length(fasta), function(i){
    data.table(CHROM=names(fasta)[i], START=1, STOP=length(fasta[[i]]), ID=i)
    data.table(CHROM=names(fasta)[i], START=1, STOP=ifelse(is.null(stop), length(fasta[[i]]), stop), ID=i)

  }))[!is.na(CHROM)]
  trimer_freq<-Nmerfrequency(features = fasta_windows, fasta=fasta, Nmer = 3, mode="counts")
  trimer_freq<-rbindlist(lapply(1:ncol(trimer_freq), function(i){
    data.table(TRI=names(trimer_freq)[i], N=sum(trimer_freq[[i]]))
  }))

  trimer_freq<-trimer_freq[!grepl("ID|N|V", TRI)]
}

make_tree<-function(mutations){
    mutations_matrix<-mutations
  mutations_matrix<-data.table(table(UNIQUE=mutations_matrix$UNIQUE, Source=mutations_matrix$SOURCE))
  mutations_matrix<-dcast(mutations_matrix, Source~UNIQUE)
  mutations_matrix<-as.matrix(mutations_matrix)
  row.names(mutations_matrix)<-mutations_matrix[,1]
  mutations_matrix<-mutations_matrix[,-1]

  # Assume mutations_matrix is already defined (row names are Samples, colnames are UNIQUE)
  # Rows: samples, Columns: mutations

  # Step 1: Convert the binary mutation matrix into a phyDat object
  phy_data <- phyDat(mutations_matrix, type = "USER", levels = c(0, 1))

  # Step 2: Create a distance matrix using binary distances
  dist_matrix <- dist(mutations_matrix, method = "binary")

  # Step 3: Generate a UPGMA tree from the distance matrix
  tree <- upgma(dist_matrix)
  #plot(tree)

  fun <- function(x) upgma(dist.ml(x))

  tree <- upgma(dist.ml(phy_data))
   
  bs_upgma <- bootstrap.phyDat(phy_data,  fun, bs = 1e4)
  plotBS(tree, bs_upgma, main="UPGMA")
  tree_with_bs <- plotBS(tree, bs_upgma, main="UPGMA")  
  
  # Step 4: Calculate branch lengths based on unique mutations
  # Initialize branch lengths
  branch_lengths <- numeric(nrow(tree_with_bs$edge))

  branch_muts<-c()
  # Traverse each edge and calculate the unique mutations
  for (i in seq_len(nrow(tree_with_bs$edge))) {
    message(i)
    node1 <- tree_with_bs$edge[i, 1]
    node2 <- tree_with_bs$edge[i, 2]

    # Get the tips (samples) downstream of node2
    descendants <- Descendants(tree_with_bs, node2, type = "tips")[[1]]


    # Get the tip labels corresponding to these descendants
    tips_in_branch <- tree_with_bs$tip.label[descendants]
    message(paste0(rownames(mutations_matrix)[descendants], collapse=" "))
    # Identify the columns in mutation_matrix that correspond to these tips
    tip_indices <- match(tips_in_branch, row.names(mutations_matrix))

    # Subset the mutation matrix for these tips
    relevant_mutations <- (mutations_matrix[tip_indices,])
    if(length(tip_indices)==1){
      relevant_mutations<-matrix(relevant_mutations, nrow=1)
    }
    relevant_mutations <- apply(relevant_mutations, 2, as.numeric)
    if(length(tip_indices)==1){
      relevant_mutations<-matrix(relevant_mutations, nrow=1)
    }
    out_relevant_mutations <- (mutations_matrix[-tip_indices,])
    if(length(tip_indices)==length(tree_with_bs$tip.label)-1){
      out_relevant_mutations<-matrix(out_relevant_mutations, nrow=1)
    }
    out_relevant_mutations <- apply(out_relevant_mutations, 2, as.numeric)
    if(length(tip_indices)==length(tree_with_bs$tip.label)-1){
      out_relevant_mutations<-matrix(out_relevant_mutations, nrow=1)
    }

    # Count mutations that are unique to this branch (present in at least one tip downstream, absent in others)
    group_mutations <- apply(relevant_mutations, 2, function(x) all(x==1))

    non_outgroup_mutations <- apply(out_relevant_mutations, 2, function(x) !any(x==1))
    group_mutations_names<-colnames(mutations_matrix)[which(group_mutations)]

    group_mutations_names<-colnames(mutations_matrix)[which(group_mutations & non_outgroup_mutations)]

    branch_muts<-c(branch_muts, group_mutations_names)
    unique_mutations<-sum(group_mutations & non_outgroup_mutations)
    # Set the branch length to the count of unique mutations
    branch_lengths[i] <- sum(unique_mutations)
  }
  branch_muts<-unique(branch_muts)
  # Step 5: Assign calculated branch lengths to the tree
  tree_with_bs$edge.length <- branch_lengths
  tree_with_bs$tip.color<-ifelse(tree_with_bs$tip.label %in% c("ref_chandler","tree2"), "tree",
                         ifelse(tree_with_bs$tip.label %in% c("cr10","cr13","cr22","cr85"), "shoot", "embryo"))

  # Ensure the tip labels and colors are stored correctly in the tree object
  tree_with_bs$tip.label <- as.character(tree_with_bs$tip.label)
  
  tree_with_bs$tip.label <- new_labels[tree_with_bs$tip.label]

  # Create a data frame from the tree object for easier mapping of colors
  tip_data <- data.frame(label = tree_with_bs$tip.label, color = tree_with_bs$tip.color)
  
#   # Attach node.label to your tree data if necessary
 node_data <- as.data.frame(tree_with_bs$node.label)
 node_data$node <- (1 + length(tree_with_bs$tip.label)):(length(tree_with_bs$tip.label) + length(tree_with_bs$node.label))
 node_data <- node_data %>%
   rename(`tree_with_bs$node.label` = "bootstrap" )


# Now, create the plot with the modified data
p <- ggtree(tree_with_bs, branch.length = "edge.length", layout = "roundrect", size = 0.25) %<+% tip_data +
    geom_tiplab(aes(label = label, fill = color),
                geom = "label",
                size = 2,
                align = FALSE,
                offset = -0.3, linesize = 0.25) +

    scale_fill_manual(values = source_type_colors, name = NULL,
                      labels = c("Embryo", "Shoot", "Tree"),
                      guide = guide_legend(override.aes = list(label = ""))) +
    theme_tree2() +
    theme(text = element_text(size = 8),
          legend.position = c(0.1, 0.75),
          legend.key.size = unit(0.25, "cm"))

p <- p %<+% node_data

p <- p + geom_text(aes(label = bootstrap), hjust = 1, vjust = -0.4, size = 2)

print(p)
 
# Cladogram

 c <- ggtree(tree_with_bs, branch.length = "none", size=0.25) %<+% tip_data +# Use the `%<+%` operator to attach data
   geom_tiplab(aes(label = label, fill = color),
               geom = "label",
               size = 2,
               align = FALSE,
               offset = -.4, linesize = 0.25) +  # Add tip labels as boxes
#   #geom_text2(aes(label = branch.length), vjust = 1.5, hjust = 1.5, size = 2, col = "red") +  # Add branch length labels
   scale_fill_manual(values = source_type_colors,
                     name=NULL,
                     labels=c("Embryo","Shoot","Tree"),
                     guide = guide_legend(override.aes = list(label = ""))) +
   theme_tree2() +
   theme(text = element_text(size = 6), legend.position = c(0.1, 0.75), legend.key.size = unit(0.25,"cm"),
         axis.title.x = element_blank(),      # Remove x-axis title
       axis.text.x = element_blank(),       # Remove x-axis text
       axis.ticks.x = element_blank(),      # Remove x-axis ticks
       axis.line.x = element_blank()        #  Remove x-axis line
   )

 
 c <- c %<+% node_data
 c <- c + geom_text(aes(label = bootstrap), hjust = 1, vjust = -0.4, size = 2)
 
 print(c)

  return(list(tree=tree, plot=p, cladogram=c, branch_muts=branch_muts, bs_upgma=bs_upgma, tips = tip_data, nodes = node_data))
}
```

## Read in data
```{r}
mutations <- fread("./Data/VCFs/Parsed/mutations.tsv")
```


## Color palette
```{r}
source_type_colors <- c("embryo"="goldenrod1", "shoot"="darkseagreen2","tree"="darkseagreen4")
```

## New labels
```{r}
new_labels = c("ref_chandler" = "Reference", "tree2" = "Tree 2",
                              "cr2_hifi" = "Embryo\nHiFi", "cr21_1" = "Embryo 1", "cr21_2" = "Embryo 2",
                              "cr2_11A" = "Embryo 11A", "cr2_12A" = "Embryo 12A", "cr2_13A" = "Embryo 13A",
                              "cr2_15A" = "Embryo 15A", "cr2_15A1" = "Embryo 15A1", "cr2_16A" = "Embryo 16A",
                              "cr2_16A1" = "Embryo 16A1", "cr2_16A2" = "Embryo 16A2", "cr2_17A1" = "Embryo 17A1",
                              "cr2_17A2" = "Embryo 17A2", "cr2_18A" = "Embryo 18A", "cr2_18A1" = "Embryo 18A1",
                              "cr85" = "Chandler '85", "cr10" = "Chandler '10", "cr13" = "Chandler '13",
                              "cr22" = "Chandler '22")
```



## Plot
```{r}
mutations_filt <- mutations[medQUAL >= 25 & medDPREAL >= 10 & MAPP==T & SNP == T]

tree<-make_tree(mutations_filt)

exp_tree<-tree$tree

tips <- tree$tips

nodes <- tree$node_data

plot <- tree$p

plot +
geom_text2(aes(label = node), hjust = -0.3, size = 3)

plot_new <- rotate(plot, 27)

plot_new <- rotate(plot_new, 37)

plot_new +
  theme(legend.position = c(.05,.85))
ggsave("./Figures/Phylogeny/all_sample_branch_is_mut.pdf", height = 4, width = 7)

clad <- tree$cladogram
  
clad_new <- rotate(clad, 27)

clad_new
ggsave("./Figures/Phylogeny/all_sample_cladogram.pdf", height = 6, width = 6.2)
```

## Playing with plotting
```{r}
p <- ggtree(exp_tree, branch.length = "edge.length", layout = "dendrogram", size = 0.25) %<+% tips +
    geom_tiplab(aes(label = label, fill = color),
                geom = "label",
                size = 2,
                align = FALSE,
                offset = -0.3, linesize = 0.25) +

    scale_fill_manual(values = source_type_colors, name = NULL,
                      labels = c("Embryo", "Shoot", "Tree"),
                      guide = guide_legend(override.aes = list(label = ""))) +
    theme_tree2() +
    theme(text = element_text(size = 8),
          legend.position = c(0.1, 0.75),
          legend.key.size = unit(0.25, "cm"))

p

p <- p %<+% nodes

p <- p + geom_text(aes(label = bootstrap), hjust = 1, vjust = -0.4, size = 2)

print(p)
```

